### ISSUE TITLE
Generate - new version phpstorm

### ISSUE THREAD

**Issue by JanGalek** [jiripudil/intellij-nette-factory-generator#2]
PhpStorm 2017.1
Build #PS-171.3780.104, built on March 21, 2017
Licensed to Jan Galek
JRE: 1.8.0_112-release-736-b13 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
Windows 10 10.0

Comments:

`AWT events are not allowed inside write action: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.ActionCallback$$Lambda$266/14187819@b13751,notifier=null,catchExceptions=false,when=1490341021636] on sun.awt.windows.WToolkit@406d51`

Details:

`AWT events are not allowed inside write action: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.ActionCallback$$Lambda$266/14187819@b13751,notifier=null,catchExceptions=false,when=1490341021636] on sun.awt.windows.WToolkit@406d51
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.impl.NoSwingUnderWriteAction.a(NoSwingUnderWriteAction.java:36)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:376)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1679)
	at java.awt.Component.setVisible(Component.java:1631)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at cz.jiripudil.intellij.nette.factoryGenerator.ui.GenerateFactoryInterfaceDialog.create(GenerateFactoryInterfaceDialog.java:67)
	at cz.jiripudil.intellij.nette.factoryGenerator.intention.GenerateFactoryInterfaceIntention.invoke(GenerateFactoryInterfaceIntention.java:36)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.invoke(PsiElementBaseIntentionAction.java:42)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.invoke(IntentionActionWrapper.java:65)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:196)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:91)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:198)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.b(ShowIntentionActionsHandler.java:186)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:185)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:184)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.b(IntentionListStep.java:273)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1396)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by jiripudil** [comment]
Thanks for the report! I'll take a look at it this weekend

As a note to self, throwing in a bunch of links that might be helpful:

- https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000020584-IJ-2017-AWT-events-are-not-allowed-inside-write-action
- https://youtrack.jetbrains.com/issue/KT-15924

**Comment by JanGalek** [comment]
I look to log report, and problem is on lines: [GenerateFactoryInterfaceIntention.java#36](https://github.com/jiripudil/intellij-nette-factory-generator/blob/master/src/cz/jiripudil/intellij/nette/factoryGenerator/intention/GenerateFactoryInterfaceIntention.java#L36) and [GenerateFactoryInterfaceDialog.java#67](https://github.com/jiripudil/intellij-nette-factory-generator/blob/master/src/cz/jiripudil/intellij/nette/factoryGenerator/ui/GenerateFactoryInterfaceDialog.java#L67)

and maybe help - 
[something like this](https://github.com/JetBrains/kotlin/commit/70c5d8b9ad6efa45a4282c9bfa2d2bfe3e0661f7?diff=unified#diff-407ad5d56e57f878b8258745a92b3a4c)
override fun startInWriteAction() = false

but I dont know java :/

**Comment by jiripudil** [comment]
Yep, I've found that too, I guess it might be the way to go. Thanks :)

**Comment by jiripudil** [comment]
Thanks, it really seems to have fixed it. I'll release 1.1.1 in a minute :)

**Comment by f3l1x** [comment]
Thank you.
